#pragma once

#define BOOST_DI_CFG_CTOR_LIMIT_SIZE 20

#include <filesystem>
#include <iostream>
#include <stdlib.h>
#include <string>
#include <string.h>
#include <numbers>
#include <format>
#include <vector>
#include <regex>
#include <random>
#include <cmath>
#include <set>
#include <map>
#include <thread>
#include <fstream>
#include <climits>
#include <time.h>
#include <sstream>
#include <cerrno>
#include <nlohmann/json.hpp>
#include <memory>
#include <array>
#include <string_view>
#include <cstring>
#include <utility>
#include <cstdint>
#include <glm/glm.hpp>
#include <glm/vec4.hpp>
#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtc/type_ptr.hpp>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/gtx/quaternion.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/transform.hpp>
#include <boost/di.hpp>